config/routes.rb
Rails.application.routes.draw do

  resources :cookbooks do
    resources :recipes, except: [:index]
    resources :subscriptions, only: [:create, :destroy, :test]
  end
  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :searches, only: [:create, :show]

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')  
  get 'subscriptions/test', to: 'subscriptions#test'
  get    '/signup',  to: 'users#new'
  post	 '/signup',	 to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  include PgSearch
  multisearchable :against => [:title, :ingredients, :steps]
  belongs_to :cookbook
  validates :title, :presence => true
  mount_uploader :image, ImageUploader  
  scope :public_entry, -> { joins(:cookbook).where(cookbooks: {public: true} ) } 
  self.per_page = 3

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @cookbook = Cookbook.find(params[:cookbook_id])
  	@recipe = Recipe.new
  end

  def create
  	params.permit!
  	@recipe = Recipe.create(cookbook_id: params[:cookbook_id])
  	@recipe.update(params[:recipe])
  	redirect_to cookbook_path(params[:cookbook_id])
  end

  def edit
    @cookbook = Cookbook.find(params[:cookbook_id])    
  	@recipe = Recipe.find(params[:id])
  end

  def update
  	params.permit!
  	@recipe = Recipe.find(params[:id])
  	@recipe.update(params[:recipe])
  	redirect_to cookbook_path(@recipe.cookbook)
  end

  def show
    @cookbook = Cookbook.find(params[:cookbook_id])    
  	@recipe = Recipe.find(params[:id])
  end

  def destroy
    @cookbook = Recipe.find(params[:id]).cookbook
  	Recipe.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to cookbook_path(@cookbook) }
      format.js { }
    end
  end
  
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_edit_form.html.erb
<%= form_for [@cookbook, @recipe] do |f| %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br><br>
	<%= f.label :image %><br>
	<%= f.file_field :image %><br><br>
	<%= f.label :ingredients %><br>
	<% i_num = 0 %>
	<% @recipe.ingredients.length.times do %>
		<%= f.text_field :ingredients, multiple: true, value: @recipe.ingredients[i_num] %><% i_num += 1 %><br>
	<% end %><br>
	<%= f.label :steps %><br>
	<% s_num = 0 %>
	<% @recipe.steps.length.times do %>
		<%= f.text_field :steps, multiple: true, value: @recipe.steps[s_num] %><% s_num += 1 %><br>
	<% end %><br>
	<%= f.submit class: "btn btn-primary col-md-12" %><br><br>
<% end %>
<br>

app/views/recipes/_form.html.erb
<%= form_for [@cookbook, @recipe] do |f| %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br><br>
	<%= f.label :image %><br>
	<%= f.file_field :image %><br><br>
	<%= f.label :ingredients %><br>
	<%= f.text_field :ingredients, multiple: true %><br>
	<%= f.text_field :ingredients, multiple: true %><br>
	<%= f.text_field :ingredients, multiple: true %><br><br>
	<%= f.label :steps %><br>
	<%= f.text_field :steps, multiple: true %><br>
	<%= f.text_field :steps, multiple: true %><br>
	<%= f.text_field :steps, multiple: true %><br><br>
	<%= f.submit class: "btn btn-primary col-md-12" %>
<% end %>
<br><br>

app/views/recipes/_recipelist.html.erb
<% @recipes.each do |recipe| %>
	<div class="col-md-12 recipe-table">
		<div class="col-md-3">
			<% if recipe.image.blank? %>
				<img src="http://image.flaticon.com/icons/png/512/45/45332.png" class="recipe-resize">
			<% else %>
				<%= image_tag(recipe.image.url, :class => "recipe-resize") %>
			<% end %>
		</div>
		<div class="col-md-9">
			<h4><%= recipe.title %>
				<% if logged_in? %>
					<% if current_user == recipe.cookbook.user || current_user.the_admin? %>
						<% if current_user == recipe.cookbook.user %>	
							[<%= link_to "Edit", edit_cookbook_recipe_path(recipe.cookbook, recipe) %>]&nbsp;
						<% end %>
					[<%= link_to "Delete", cookbook_recipe_path(recipe.cookbook, recipe), method: :delete %>]&nbsp;
					<% end %>
				<% end %>
				[<%= link_to "View Cookbook", cookbook_path(recipe.cookbook) %>]
			</h4><br>

			<table>
				<tr>
					<td class="col-md-4">
						<b>Ingredients:</b>
						<ul>
							<% recipe.ingredients.each do |x| %>
								<li><%= x %></li>
							<% end %>
						</ul>
					</td>
					<td class="col-md-4">
						<b>Steps:</b>
						<ol>
							<% recipe.steps.each do |y| %>
								<li><%= y %></li>
							<% end %>
						</ol>
					</td>
				</tr>
			</table>
		</div>
	</div>
<% end %>

app/views/recipes/edit.html.erb
<% @title="WC? | Edit Recipe" %>
<div class="white-bg col-md-5">
	<h1>Edit: <%= @recipe.title %></h1>
	<% if current_user == @cookbook.user %>
		<%= render 'edit_form' %>
	<% else %>
		You are not permitted to edit this recipe.
	<% end %>
</div>

app/views/recipes/new.html.erb
<% @title="WC? | New Recipe" %>
<div class="white-bg col-md-5">
	<h1>Create New Recipe</h1>
	<% if current_user == @cookbook.user %>
		<%= render 'form' %>
	<% else %>
		You are not permitted to add recipes to this cookbook.
	<% end %>
	<br>
</div>