config/routes.rb
Rails.application.routes.draw do

  resources :cookbooks do
    resources :recipes, except: [:index]
    resources :subscriptions, only: [:create, :destroy, :test]
  end
  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :searches, only: [:create, :show]

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')  
  get 'subscriptions/test', to: 'subscriptions#test'
  get    '/signup',  to: 'users#new'
  post	 '/signup',	 to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cookbook.rb
class Cookbook < ApplicationRecord
  include PgSearch
  multisearchable :against => [:title, :description]
  belongs_to :user
  validates :title, :presence => true
  has_many :recipes
  has_many :subscriptions, dependent: :destroy
  mount_uploader :book_cover, BookCoverUploader  
  scope :public_entry, -> { where public: true }  
  self.per_page = 4

end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController

  def index
    if params[:view] == "all" || current_user.the_admin?
      @status = "all" if params[:view] == "all"
      @cookbooks = Cookbook.all.public_entry.page(params[:page]).order('created_at DESC')
    else
  	 @cookbooks = Cookbook.where(user_id: current_user.id).page(params[:page]).order('created_at DESC')
    end
  end

  def new
  	@cookbook = Cookbook.new
  end

  def create
  	params.permit!
  	@cookbook = Cookbook.create(user_id: current_user.id)
  	@cookbook.update(params[:cookbook])
  	redirect_to cookbooks_path
  end

  def show
    @recipes = Recipe.where(:cookbook_id => params[:id]).page(params[:page]).order('created_at DESC')
  	@cookbook = Cookbook.find(params[:id])
  end

  def edit
  	@cookbook = Cookbook.find(params[:id])
  end

  def update
  	params.permit!
  	@cookbook = Cookbook.find(params[:id])
  	@cookbook.update(params[:cookbook])
  	redirect_to cookbooks_path  	
  end

  def destroy
  	Cookbook.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to cookbooks_path }
      format.json { head :no_content }
      format.js   { render :nothing => true }
    end
  end
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/views/cookbooks/_cookbooklist.html.erb
<% @cookbooks.each do |book| %>
	<div class="col-md-3 new-book" align="center">
		<div class="ind-book"><br>
			<% if book.book_cover.blank? %>
				<img src="http://i64.tinypic.com/qxmqfn.jpg" class="bookcover-resize">
			<% else %>
				<%= image_tag(book.book_cover.url, :class => "bookcover-resize") %>
			<% end %><br>
			<h3><%= link_to book.title, cookbook_path(book) %></h3>
			<%= book.description %><br><br>
			<% if logged_in? %>
				<% if current_user == book.user || current_user.the_admin? %>
					<% if current_user == book.user %>	
						<%= button_to "Edit", edit_cookbook_path(book), method: :get, class: 'btn btn-warning' %>
					<% end %>
					<%= button_to 'Del', cookbook_path(book), method: :delete, remote: :true, :class=>'btn btn-danger delete_post' %> 
					<%= button_to "See", cookbook_path(book), method: :get, class: 'btn btn-success' %>
				<% end %>
			<% end %>
		</div>
		<br><br>
	</div>
<% end %>

<script>
	$( ".delete_post" ).click(function() {
	  $( ".newbook" ).remove();
	});
</script>

app/views/cookbooks/_form.html.erb
<%= form_for @cookbook do |f| %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br><br>
	<%= f.label :description %><br>
	<%= f.text_field :description %><br><br>
	<%= f.label :book_cover %><br>
	<%= f.file_field :book_cover %><br><br>
	<%= f.radio_button :public, true, :checked => true %>
	<%= label :public_yes, 'Public' %>      
	<%= f.radio_button :public, false %>
	<%= label :public_no, 'Private' %><br><br>
	<%= f.submit class: 'btn btn-primary col-md-12' %><br>
<% end %>

app/views/cookbooks/edit.html.erb
<% @title="WC? | Edit Cookbook" %>

<div class="white-bg col-md-5">
	<h1>Edit: <%= @cookbook.title %></h1>
	<% if current_user == @cookbook.user %>
		<%= render 'form' %>
	<% else %>
		You are not permitted to edit this cookbook.
	<% end %>
	<br><br>
</div>

app/views/cookbooks/index.html.erb
<% @title="WC? | Cookbooks" %>

<h1 align="center">
<% if @status == "all" %>
	List of Cookbooks
<% else %>
	My Cookbooks
<% end %>
</h1>
<h4 align="center"><%= will_paginate @cookbooks %></h4>
<% if current_user != nil %>
	<% if !current_user.the_admin? %>
		<%= button_to "Create Cookbook", new_cookbook_path, method: :get, class: "btn btn-primary col-md-12" %>
	<% end %>
<% end %>

<%= render 'cookbooklist' %>

app/views/cookbooks/new.html.erb
<% @title="WC? | New Cookbook" %>

<div class="white-bg col-md-5">
	<h1>Create New Cookbook</h1>
	<%= render 'form' %>
	<br><br>
</div>

app/views/cookbooks/show.html.erb
<% @title="WC? | #{@cookbook.title}" %>

<% if @cookbook.public == true || current_user == @cookbook.user %>

	<div align="center">
		<h1><%= @cookbook.title %></h1>
		<p>by <%= link_to @cookbook.user.username, user_path(@cookbook.user) %></p>
	</div>

	<h4 align="center"><%= will_paginate @recipes %></h4>
	<% if logged_in? %>
		<% if current_user == @cookbook.user %>
			<%= button_to "Add Recipe", new_cookbook_recipe_path(@cookbook), method: :get, class: "btn btn-primary col-md-12" %>
		<% else %>
			<% if @cookbook.subscriptions.find_by(user_id: current_user.id) == nil %>
			<span id="subscribe">
				<%= button_to "Subscribe", cookbook_subscriptions_path(@cookbook), class: 'btn btn-primary btn-block', remote: true %>
			</span>
			<% else %>
			<span id="unsubscribe">
				<%= button_to "Unsubscribe", cookbook_subscription_path(cookbook_id: @cookbook.id, user_id: current_user.id), method: :delete, class: "btn btn-primary btn-block btn-custom", remote: true %>
			</span>				
			<% end %>
			<span id="subscription-success" style="display: none">
				<%= button_to "Unsubscribe", cookbook_subscription_path(cookbook_id: @cookbook.id, user_id: current_user.id), method: :delete, class: "btn btn-primary btn-block btn-custom", remote: true %>
			</span>
			<span id="subscription-cancel" style="display: none">
				<%= button_to "Subscribe", cookbook_subscriptions_path(@cookbook), class: 'btn btn-primary btn-block', remote: true %>
			</span>
		<% end %>
	<% end %>
	<br>
	<u>Subscribers:</u>
	<div id="subscriber-list">
		<% if @cookbook.subscriptions.count > 0 %>
			<% num = 0 %><br>
			<% @cookbook.subscriptions.all.each do |subscribers| %>
				<% @subscribed_user = User.find(subscribers.user_id) %>
				<a href="/users/<%= subscribers.user_id %>">
					<% if @subscribed_user.avatar.blank? %>
						<img src="http://i452.photobucket.com/albums/qq244/missnpk93/defaultuser_zpsnsqypglf.png" class="subscriber-resize" title="<%= @subscribed_user.username %>">
					<% else %>
						<%= image_tag(@subscribed_user.avatar.url, :class => "subscriber-resize", title: @subscribed_user.username) %>
					<% end %>
				</a>
				<% num += 1 %>
				<% if num >= 10 %>
					<b>+</b>
					<break>
				<% end %>
			<% end %>
		<% else %>
		<span id="no-subscriber">
			<img src="http://www.publicdomainpictures.net/pictures/40000/velka/question-mark.jpg" class="subscriber-resize" title="No Subscribers Yet!">
		</span>
		<% end %>
		<span id='new-subscriber'></span>
	</div>

	<br>

	<%= render :partial => 'recipes/recipelist' %>

	<br>

<% else %>

	<div class="notice">
		<p>Sorry, the user has privated this cookbook.</p>
	</div>

<% end %>