config/routes.rb
Rails.application.routes.draw do

  resources :cookbooks do
    resources :recipes, except: [:index]
    resources :subscriptions, only: [:create, :destroy, :test]
  end
  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :searches, only: [:create, :show]

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')  
  get 'subscriptions/test', to: 'subscriptions#test'
  get    '/signup',  to: 'users#new'
  post	 '/signup',	 to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="nav-side-menu">

  <!-- Title, avatar/logo and welcome message -->
  <div class="brand">
    <h2>What's Cooking?</h2>
    <% if !logged_in? %>
      <img src="http://image.flaticon.com/icons/png/512/45/45332.png" width="100px" height="100px" style="margin-bottom: 10px; margin-top: 10px">
    <% else %>
      <% if current_user.avatar.blank? %>
        <img src="http://i452.photobucket.com/albums/qq244/missnpk93/defaultuser_zpsnsqypglf.png" class="avatar-resize">
      <%else%>
        <%= image_tag(current_user.avatar.url, :class => "avatar-resize") %>
      <% end %>
      <br>Hi <%= link_to current_user.username, user_path(current_user) %>! (<%= link_to "Edit Profile", edit_user_path(current_user) %>)
    <% end %>

  <!-- Search bar -->
    <%= form_tag(controller: "searches", action: "create", method: "post") do %>
      <%= text_field_tag(:query, nil, :class => "searchbox") %>
      <%= submit_tag("Search", :id=>"button", :class=>"btn btn-default", :name=>"submit") %>
    <% end %>
  </div>


  <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
  
  <div class="menu-list">
    <ul id="menu-content" class="menu-content collapse out">
      <li>
        <a href="#">
          <i class="fa fa-dashboard fa-lg"></i>
            <% if !logged_in? %>
              <a href="#" data-toggle="modal" data-target="#myModal"> Sign In / Register </a>
            <% else %>
              <%= link_to "Sign Out", logout_path, method: :delete %>
            <% end %>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-folder-open-o"></i>
            <%= link_to "All Cookbooks", cookbooks_path(view: "all") %>
        </a>
      </li>
      <% if logged_in? %>
        <li  data-toggle="collapse" data-target="#products" class="collapsed">
        <a href="#"><i class="fa fa-gift fa-lg"></i> My Cookbooks <span class="arrow"></span></a>
        </li>
        <ul class="sub-menu collapse" id="products">
          <li><%= link_to "VIEW ALL", cookbooks_path %></li>
            <% if current_user.cookbooks.length > 0 %>
              <% current_user.cookbooks.each do |x| %>
                <li><%= link_to x.title, cookbook_path(x) %></li>
              <% end %>
            <% end %>
        </ul>

        <li data-toggle="collapse" data-target="#service" class="collapsed">
          <a href="#"><i class="fa fa-globe fa-lg"></i>My Subscriptions<span class="arrow"></span></a>
        </li>  
        <ul class="sub-menu collapse" id="service">
          <% if Subscription.where(user_id: current_user.id).count > 0 %>
            <% current_user.subscriptions.each do |x| %>
              <li><%= link_to Cookbook.find(x.cookbook_id).title, cookbook_path(x.cookbook_id) %></a></li>
            <% end %>
          <% else %>
              <li>None! Start subscribing one today!</li>
          <% end %>
        </ul>
      <% end %>
    </ul>

    <div class="intro">
      <p><i>Was it 100g or 200g?</i>Cooking is such an intricate task that sometimes we might forgot all the little details that makes the perfect dish.</p>
      <p><strong>What's Cooking</strong> is a platform for users to keep track of their favourite recipes without the fear misplacing it. Start posting, viewing and subscribing to your favourite recipes NOW!</p>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>

                </button>
                 <h4 class="modal-title" id="myModalLabel">User Authentication</h4>

            </div>
            <div class="modal-body">
                <div role="tabpanel">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#uploadTab" aria-controls="uploadTab" role="tab" data-toggle="tab">Sign In</a>

                        </li>
                        <li role="presentation"><a href="#browseTab" aria-controls="browseTab" role="tab" data-toggle="tab">Register</a>

                        </li>
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="uploadTab"><%= render :partial => 'sessions/form' %></div>
                        <div role="tabpanel" class="tab-pane" id="browseTab"><%= render :partial => 'users/newform' %></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= @title %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="icon" type="image/png" href="http://image.flaticon.com/icons/png/512/45/45332.png" />
    </head>

    <body>
        <div class="col-xs-5 col-sm-5 col-md-3">
            <%= render :partial => 'layouts/navbar' %>
        </div>
        <div class="col-xs-7 col-sm-7 col-md-9">
            <%= yield %>
        </div>
    </body>
    
</html>